### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by ryo1116** [kd2014-test1/sp-web#1]
TOPページに描こうと思っている各メニューとWORKS画像の更生案を2パターン使って比較したいと思います。
- [ ] パターンA
- [ ] パターンB

**Comment by ryo1116** [comment]
WORKS画像の閲覧方法は縦にスクロールするタイプと、1枚を横にスライドショー風に大きく見せる２つのタイプがあると良いと思います。

**Comment by yosi1205** [comment]
それなら各メニューは縦スクロールなら上部に小さく、横スライドショーなら下部に大きく並べてみてはどうですか。

**Comment by ryo1116** [comment]
ヘッダーとフッターはどうしましょうか？

**Comment by yosi1205** [comment]
とりあえずヘッダーには弊社ロゴを入れておいて、フッターは縦スクロールにだけ入れれば問題ないと思います。

**Comment by ryo1116** [comment]
そうですね。横スライドショーさせるほうは、WORKSの画像をなるべく大きく見せるためにフッターは削ってみるのがよいと思います。
